<a href="https://colab.research.google.com/github/Mysterio-maker/STUDY-OF-NUMPY-IN-PYTHON/blob/main/EXPERIMENT_8_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#EXPERIMENT - 8

## TITLE- TOOLS FOR EDA- NUMPY

## AMEY WAGHMARE
## 25070123009
## A1

In [ ]:
 import numpy as np



a = np.array([10,20,30,40])
b = np.array([[1,2,3,4],[2,3,4,5]])

print(a)
print(b)


[10 20 30 40]
[[1 2 3 4]
 [2 3 4 5]]


In [ ]:
a.ndim

1

In [ ]:
b.ndim


2

In [ ]:
a.shape

(4,)

In [ ]:
b.shape

(2, 4)

In [ ]:
a.dtype

dtype('int64')

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.eye((7))

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
np.arange(2,20,7)

array([ 2,  9, 16])

In [ ]:
np.linspace(0,7,5)

array([0.  , 1.75, 3.5 , 5.25, 7.  ])

In [ ]:
a+7


array([17, 27, 37, 47])

In [ ]:
a*7

array([ 70, 140, 210, 280])

In [ ]:
c=a+7
d=a*7

print(c)
print(d)

[17 27 37 47]
[ 70 140 210 280]


In [ ]:
np.mean(a)

np.float64(25.0)

In [ ]:
np.mean(b)

np.float64(3.0)

In [ ]:
np.median(a)

np.float64(25.0)

In [ ]:
np.median(b)

np.float64(3.0)

In [ ]:
np.max(a)

np.int64(40)

In [ ]:
np.max(b)

np.int64(5)

In [ ]:
np.min(a)

np.int64(10)

In [ ]:
np.min(b)

np.int64(1)

In [ ]:
np.sum(a)

np.int64(100)

In [ ]:
np.sum(b)

np.int64(24)